# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b88cc76fc0dea0627e5d9fd31e32b2bbd0db27b10f04022b9587a4b83ab227afb00ed629010306f50b39d5a8ca21b1c79b543046cca38b27000f26aa76d2761

test:
  secret_key_base: 2a88162ebb249a9b1c1a0ad85d6bb4cf703a172f9fb11843a4bfd946dd61ee6fd61e0394474e5e83e4fd07234d6c2460bf67c13a63cf1aea7323001c945fad67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
